### ISSUE TITLE
Transformations

### ISSUE THREAD

**Issue by skaae** [bordingj/Mowgly#2]
# hardcoded_scaling
https://github.com/bordingj/Mowgly/blob/f89843ff2e5cdb8cb6a08fd45663c1cca758886e/mowgly/transformation/hardcoded_scaling.py#L33
Jeg synes den skal hedde Normalize fordi jeg ellers ville forvente at et offset blev lagt til. 
og ændre
```
        :param input_name2rescalings: mapping from input_name to dict of feature_name->(mean,std) mappings. if mean or std is None the value is ignored.
````
evt
```python
if offset is not None
                input[feat_name] -= offset
if offset is not None
                input[feat_name] /= normalizer
```

# class LogTransformation(Step):
Kan man ikke omdøbde den til LambdaTransformation og lade den tage en lamda funktion/numpy funktion som input? Evt bare lave LogTransformation som en special case?

**Comment by skaae** [comment]
https://github.com/bordingj/Mowgly/blob/5c134ddd6948888d4e496b1c12b55b23e21aa9b2/mowgly/transformation/sigmoid_transformation.py#L7
Kunne også være en special case af Lambda ? 

fx 

```Python
class LambdaTransformation(Step):
    def __init__(self, input_name2feature_names, lambda_func,  copy=False)

...
#End of class

class LogTransformation(LambdaTransformation):
    def __init__(self, input_name2feature_names,  copy=False)
          super(self, LambdaTransformation).__init__(self, input_name2feature_names,  lambda_func=np.log, copy=copy)

class TanhTransformation(LambdaTransformation):
    def __init__(self, input_name2feature_names,  copy=False)
          super(self, LambdaTransformation).__init__(self, input_name2feature_names,  lambda_func=np.tanh, copy=copy)

```

**Comment by skaae** [comment]
I https://github.com/bordingj/Mowgly/blob/d8e0a440fb4d0fb979be2d29672349c571fa78bf/mowgly/transformation/nan_filling.py#L39

Hvis man har en NaN før første værdi så vil forward fill vel stadig efterlade dem som nans? 

Jeg ved ikke om man først skal forwardfille og så backward fille for at fange det? eller lave en backwardfill class?

**Comment by bordingj** [comment]
> Jeg synes den skal hedde Normalize fordi jeg ellers ville forvente at et offset blev lagt til.
og ændre

skal vi ikke bare ændre det til at offset bliver lagt til så ?
synes ikke man skal lave det der None-check. De skal ikke være None. Hvis ikke man er interesseret i at apply'e denne rescaling til en feature skal den jo bare ikke være i dictionary'en. 

> Kunne også være en special case af Lambda ?

Enig - det ændrer vi.

> Hvis man har en NaN før første værdi så vil forward fill vel stadig efterlade dem som nans?

Ja, vil derfor mene det er op til brugeren at sikre at første værdi ikke er nan. Men lad os introducere et tjek som tjekker på om der stadig er nans efter nan-filling.

> Jeg ved ikke om man først skal forwardfille og så backward fille for at fange det? eller lave en backwardfill class?

Jeg vil mene at man altid kun vil være interesseret i at enten at forward-fill eller backward-fill, så lad os lave en backwardfill class. Men for financial-timeseries f.eks. vil man aldrig bruge backfilling noget sted i ens pipeline.
