### ISSUE TITLE
Pipline

### ISSUE THREAD

**Issue by skaae** [bordingj/Mowgly#3]
https://github.com/bordingj/Mowgly/blob/3bef639e81c9f7b8884f31d13a1ea49a6a34b978/mowgly/pipeline.py#L49-L53

Jeg tror det skal være

```Python
 for step in self.steps: 
     inputs = step.forward(**inputs) 
return inputs
```

**Comment by skaae** [comment]
Kan du ikke også sætte `__init__` øverst? 

https://github.com/bordingj/Mowgly/blob/3bef639e81c9f7b8884f31d13a1ea49a6a34b978/mowgly/pipeline.py#L32-L34

Jeg tror det fejler hvis der kun er et step fordi `i` så er undefined.
hvad med:
```Python
for step in self.steps[:-1]:
    inputs = step.fit_forward(**inputs)
self.steps[-1].fit(**inputs)
```

hvad betyder det at man returner self?

**Comment by bordingj** [comment]
Er helt enig i alle dine rettelser.. fit returnerer self (returnerer selve instancen af klassen) fordi sådan er det også i sklearn
